### PR TITLE
Fix #7 and #8

### LINKED ISSUE #7: Remove makeRepInline
Ryan wrote:

> For what it's worth, I discovered recently while working on dreixel/generic-deriving#80 that you don't actually need this `makeRepInline` function if you only use the `derive-` functions. I'm hoping to get up a patch soon. Removing `makeRepInline` would allow removing a fair bit of needless complexity in some of the downstream functions—for instance, you wouldn't need to propagate a `TypeSubst` down to `repField` anymore.

### LINKED ISSUE #8: Add comment on kind signatures
@aspiwack points to a comment in `Generics.Linear.TH`:

```haskell
{-
If we dropped the kind signature for a in a derived instance for Fam a, then GHC
would have no way of knowing which instance we are talking about.
-}
```

He says,

> It would be worth writing a derived instance without and with a kind signature to be able to point concretely at what goes wrong.

### PR DESCRIPTION
**Pull request by RyanGlScott**
This PR contains a series of commits that fixes #7 (removing `makeRepInline`) and #8 (various comment improvements around kind signatures, including an extra test case). The fix for #7 was heavily inspired by dreixel/generic-deriving#80, which is in similar territory.

Fixes #7. Fixes #8.

### CODE REVIEW

File: src/Generics/Linear/TH.hs [hunk 1]
```diff
@@ -569,5 +570,6 @@ Why do we do this? Imagine what the instance would be without the explicit retur
   instance Generic1 S where
     type Rep1 S = ... (Rec0 k)
 
-This is an error, since the variable k is now out-of-scope!
```
Comment (treeowl) [inline src/Generics/Linear/TH.hs:580]: A few lines above it still says "return kind", because I missed it. Could you remove the mysterious "return"?

File: src/Generics/Linear/TH.hs [hunk 2]
```diff
@@ -569,5 +570,6 @@ Why do we do this? Imagine what the instance would be without the explicit retur
...
+This is an error, since the variable k is now out-of-scope! The TypeInTypeSpec
+test case checks that this behaves as intended.
```
Comment (treeowl) [inline src/Generics/Linear/TH.hs:541]: Do we need the signature on the instance head, or just the type family argument?

Comment (RyanGlScott) [reply src/Generics/Linear/TH.hs:544]: In general we need both, although this particular example only needs the kind annotation on the type family instance. I've modified the wording to be a bit more precise here.

File: src/Generics/Linear/TH.hs (hunk 1 above)
Comment (RyanGlScott) [reply src/Generics/Linear/TH.hs:580]: I've changed "explicit return kind" to "explicit kind annotation".

**Comment by treeowl** [comment]
Oh, never mind! I had a typo in my test. I accidentally wrote `$(deriveAll1 ''Fakeout)`. But that shows up a (minor) bug of its own. The error message was

```haskell
src/MyLib.hs:1:1: error:
    Exception when trying to run compile-time code:
      Generics.Deriving.TH.reifyDataInfo:  Could not reify FakeOut
CallStack (from HasCallStack):
  error, called at src/Generics/Deriving/TH.hs:337:42 in generic-deriving-1.14.1-5998e5d526b150b18e1033e5ec3bc07f6a9a9877746e23e552587324e8f86ad8:Generics.Deriving.TH
    Code: (deriveAll1 ''FakeOut)
```

which means `error` was called instead of `fail`. But I can't tell what's actually supposed to be an `error` and what's supposed to be a `fail` across the module!

**Comment by RyanGlScott** [comment]
Generally speaking, I tend to prefer `fail` over `error` in a `Q` context, as it results in more nicely formatted errors. I'm sure we could do better about enforcing this discipline in the TH code.

**Comment by treeowl** [comment]
@RyanGlScott, `error` should mean "There's a bug in the Template Haskell code", while `fail` should mean "There's a bug in the code inserting the splice." I just don't know which are which here.
